### ISSUE TITLE
False negatives for ToUnicode and CIDSet for attached PDF

### ISSUE THREAD

**Issue by DietrichSeggern** [veraPDF/veraPDF-model#143]
Attached is the PDF and a veraPDF 1.6.3 report for it. 

Validate PDF in veraPDF 1.6.3 for compliance with PDF/A-2a.
Errors for ToUnicode CMAP and CIDSet are reportet, however, both entries for all fonts listed in the veraPDF seem to be correct.

callas pdfaPilot 7.0 and PDF-Tools Online Validator validate the file successfully.

[Attachment_with_long_file_name_byPDFC_A2a.pdf](https://github.com/veraPDF/veraPDF-model/files/1102068/Attachment_with_long_file_name_byPDFC_A2a.pdf)

[Validation Report.html.zip](https://github.com/veraPDF/veraPDF-model/files/1102066/Validation.Report.html.zip)

**Comment by shem-sergey** [comment]
VeraPDF bugs concerning toUnicode and CIDSet were fixed, now this file is compliant according to the last veraPDF version.
